call make.bat skia_lib BUILDTYPE=Debug SKIA_OUT=x86 "GYP_DEFINES=skia_arch_type=x86 skia_shared_lib=0 skia_skip_gui=1 skia_angle=0 skia_codec_decodes_raw=1 skia_mesa=0 skia_vulkan=0 skia_android_framework=0 skia_static_initializers=1 skia_chrome_utils=0 skia_directwrite=1 skia_opencl=1 skia_use_sdl=0 skia_dump_stats=0"
"%VS120COMNTOOLS%..\..\VC\bin\lib.exe" /OUT:skia_x86d.lib x86/Debug/skia_core.lib x86/Debug/skia_codec.lib x86/Debug/skia_effects.lib x86/Debug/skia_images.lib x86/Debug/skia_opts.lib x86/Debug/skia_opts_ssse3.lib x86/Debug/skia_opts_sse41.lib x86/Debug/skia_ports.lib x86/Debug/skia_sfnt.lib x86/Debug/skia_skgpu.lib x86/Debug/skia_utils.lib

call make.bat skia_lib BUILDTYPE=Release SKIA_OUT=x86 "GYP_DEFINES=skia_arch_type=x86 skia_shared_lib=0 skia_skip_gui=1 skia_angle=0 skia_codec_decodes_raw=1 skia_mesa=0 skia_vulkan=0 skia_android_framework=0 skia_static_initializers=1 skia_chrome_utils=0 skia_directwrite=1 skia_opencl=1 skia_use_sdl=0 skia_dump_stats=0"
"%VS120COMNTOOLS%..\..\VC\bin\lib.exe" /OUT:skia_x86.lib x86/Release/skia_core.lib x86/Release/skia_codec.lib x86/Release/skia_effects.lib x86/Release/skia_images.lib x86/Release/skia_opts.lib x86/Release/skia_opts_ssse3.lib x86/Release/skia_opts_sse41.lib x86/Release/skia_ports.lib x86/Release/skia_sfnt.lib x86/Release/skia_skgpu.lib x86/Release/skia_utils.lib

call make.bat skia_lib BUILDTYPE=Debug SKIA_OUT=x64 "GYP_DEFINES=skia_arch_type=x86_64 skia_shared_lib=0 skia_skip_gui=1 skia_angle=0 skia_codec_decodes_raw=1 skia_mesa=0 skia_vulkan=0 skia_android_framework=0 skia_static_initializers=1 skia_chrome_utils=0 skia_directwrite=1 skia_opencl=1 skia_use_sdl=0 skia_dump_stats=0"
"%VS120COMNTOOLS%..\..\VC\bin\lib.exe" /OUT:skia_x64d.lib x64/Debug/skia_core.lib x64/Debug/skia_codec.lib x64/Debug/skia_effects.lib x64/Debug/skia_images.lib x64/Debug/skia_opts.lib x64/Debug/skia_opts_ssse3.lib x64/Debug/skia_opts_sse41.lib x64/Debug/skia_ports.lib x64/Debug/skia_sfnt.lib x64/Debug/skia_skgpu.lib x64/Debug/skia_utils.lib

call make.bat skia_lib BUILDTYPE=Release SKIA_OUT=x64 "GYP_DEFINES=skia_arch_type=x86_64 skia_shared_lib=0 skia_skip_gui=1 skia_angle=0 skia_codec_decodes_raw=1 skia_mesa=0 skia_vulkan=0 skia_android_framework=0 skia_static_initializers=1 skia_chrome_utils=0 skia_directwrite=1 skia_opencl=1 skia_use_sdl=0 skia_dump_stats=0"
"%VS120COMNTOOLS%..\..\VC\bin\lib.exe" /OUT:skia_x64.lib x64/Release/skia_core.lib x64/Release/skia_codec.lib x64/Release/skia_effects.lib x64/Release/skia_images.lib x64/Release/skia_opts.lib x64/Release/skia_opts_ssse3.lib x64/Release/skia_opts_sse41.lib x64/Release/skia_ports.lib x64/Release/skia_sfnt.lib x64/Release/skia_skgpu.lib x64/Release/skia_utils.lib

